name: CI

on:
  push:
    branches:
      - "*"
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "release/*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.7

      - name: Install node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.17.0

      - name: Install npm dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
